" vim:set ts=8 sts=2 sw=2 tw=0: (この行に関しては:help modelineを参照)
"
" An example for a Japanese version vimrc file.
" 日本語版のデフォルト設定ファイル(vimrc) - Vim7用試作
"
" Last Change: 24-Jun-2013.
" Maintainer:  MURAOKA Taro <koron.kaoriya@gmail.com>
"
" 解説:
" このファイルにはVimの起動時に必ず設定される、編集時の挙動に関する設定が書
" かれています。GUIに関する設定はgvimrcに書かかれています。
"
" 個人用設定は_vimrcというファイルを作成しそこで行ないます。_vimrcはこのファ
" イルの後に読込まれるため、ここに書かれた内容を上書きして設定することが出来
" ます。_vimrcは$HOMEまたは$VIMに置いておく必要があります。$HOMEは$VIMよりも
" 優先され、$HOMEでみつかった場合$VIMは読込まれません。
"
" 管理者向けに本設定ファイルを直接書き換えずに済ませることを目的として、サイ
" トローカルな設定を別ファイルで行なえるように配慮してあります。Vim起動時に
" サイトローカルな設定ファイル($VIM/vimrc_local.vim)が存在するならば、本設定
" ファイルの主要部分が読み込まれる前に自動的に読み込みます。
"
" 読み込み後、変数g:vimrc_local_finishが非0の値に設定されていた場合には本設
" 定ファイルに書かれた内容は一切実行されません。デフォルト動作を全て差し替え
" たい場合に利用して下さい。
"
" 参考:
"   :help vimrc
"   :echo $HOME
"   :echo $VIM
"   :version

" $HOMEの再設定
"let $HOME = 'C:\cygwin\home\y-uno\'
if has('win32')
  let $HOME = 'C:\Users\uno_y\tools\vim\'
endif

" $TEMPの再設定
"let $TEMP = 'C:\cygwin\tmp\'

" バージョン7.1以下のVimを使う場合vimrcを読み込まない
"if version < 701
"    :finish
"endif
"---------------------------------------------------------------------------
" サイトローカルな設定($VIM/vimrc_local.vim)があれば読み込む。読み込んだ後に
" 変数g:vimrc_local_finishに非0な値が設定されていた場合には、それ以上の設定
" ファイルの読込を中止する。
if 1 && filereadable($VIM . '/vimrc_local.vim')
  unlet! g:vimrc_local_finish
  source $VIM/vimrc_local.vim
  if exists('g:vimrc_local_finish') && g:vimrc_local_finish != 0
    finish
  endif
endif

"---------------------------------------------------------------------------
" ユーザ優先設定($HOME/.vimrc_first.vim)があれば読み込む。読み込んだ後に変数
" g:vimrc_first_finishに非0な値が設定されていた場合には、それ以上の設定ファ
" イルの読込を中止する。
if 0 && exists('$HOME') && filereadable($HOME . '/.vimrc_first.vim')
  unlet! g:vimrc_first_finish
  source $HOME/.vimrc_first.vim
  if exists('g:vimrc_first_finish') && g:vimrc_first_finish != 0
    finish
  endif
endif

" plugins下のディレクトリをruntimepathへ追加する。
for path in split(glob($VIM.'/plugins/*'), '\n')
  if isdirectory(path) | let &runtimepath = &runtimepath.','.path | end
endfor

"---------------------------------------------------------------------------
" 日本語対応のための設定:
"
" ファイルを読込む時にトライする文字エンコードの順序を確定する。漢字コード自
" 動判別機能を利用する場合には別途iconv.dllが必要。iconv.dllについては
" README_w32j.txtを参照。ユーティリティスクリプトを読み込むことで設定される。
if has('win32')
  source $VIMRUNTIME/plugins/kaoriya/encode_japan.vim
endif
" メッセージを日本語にする (Windowsでは自動的に判断・設定されている)
if !(has('win32') || has('mac')) && has('multi_lang')
  if !exists('$LANG') || $LANG.'X' ==# 'X'
    if !exists('$LC_CTYPE') || $LC_CTYPE.'X' ==# 'X'
      language ctype ja_JP.eucJP
    endif
    if !exists('$LC_MESSAGES') || $LC_MESSAGES.'X' ==# 'X'
      language messages ja_JP.eucJP
    endif
  endif
endif
" MacOS Xメニューの日本語化 (メニュー表示前に行なう必要がある)
if has('mac')
  if exists('$LANG') && $LANG ==# 'ja_JP.UTF-8'
    set langmenu=ja_ja.utf-8.macvim
    set encoding=utf-8
    set ambiwidth=double
  endif
endif
" 日本語入力用のkeymapの設定例 (コメントアウト)
if has('keymap')
  " ローマ字仮名のkeymap
  "silent! set keymap=japanese
  "set iminsert=0 imsearch=0
endif
" 非GUI日本語コンソールを使っている場合の設定
if !has('gui_running') && &encoding != 'cp932' && &term == 'win32'
  set termencoding=cp932
endif

"---------------------------------------------------------------------------
" メニューファイルが存在しない場合は予め'guioptions'を調整しておく
if 1 && !filereadable($VIMRUNTIME . '/menu.vim') && has('gui_running')
  set guioptions+=M
endif

"---------------------------------------------------------------------------
" Bram氏の提供する設定例をインクルード (別ファイル:vimrc_example.vim)。これ
" 以前にg:no_vimrc_exampleに非0な値を設定しておけばインクルードはしない。
if 1 && (!exists('g:no_vimrc_example') || g:no_vimrc_example == 0)
  if &guioptions !~# "M"
    " vimrc_example.vimを読み込む時はguioptionsにMフラグをつけて、syntax on
    " やfiletype plugin onが引き起こすmenu.vimの読み込みを避ける。こうしない
    " とencに対応するメニューファイルが読み込まれてしまい、これの後で読み込
    " まれる.vimrcでencが設定された場合にその設定が反映されずメニューが文字
    " 化けてしまう。
    set guioptions+=M
    source $VIMRUNTIME/vimrc_example.vim
    set guioptions-=M
  else
    source $VIMRUNTIME/vimrc_example.vim
  endif
endif

"---------------------------------------------------------------------------
" 検索の挙動に関する設定:
"
" 検索時に大文字小文字を無視 (noignorecase:無視しない)
set ignorecase
" 大文字小文字の両方が含まれている場合は大文字小文字を区別
set smartcase
" インクリメンタルサーチ
set incsearch

"---------------------------------------------------------------------------
" 編集に関する設定:
"
" タブの画面上での幅
set tabstop=4
" タブ幅
set softtabstop=4
" タブを挿入するときの幅
set shiftwidth=4
" タブをスペースに展開しない (expandtab:展開する)
set noexpandtab
" 自動的にインデントする (noautoindent:インデントしない)
set autoindent
" バックスペースでインデントや改行を削除できるようにする
set backspace=2
" 検索時にファイルの最後まで行ったら最初に戻る (nowrapscan:戻らない)
set wrapscan
" 括弧入力時に対応する括弧を表示 (noshowmatch:表示しない)
set showmatch
" コマンドライン補完するときに強化されたものを使う(参照 :help wildmenu)
set wildmenu
" テキスト挿入中の自動折り返しを日本語に対応させる
set formatoptions+=mM

"---------------------------------------------------------------------------
" GUI固有ではない画面表示の設定:
"
" 行番号を非表示 (number:表示)
set number
" ルーラーを表示 (noruler:非表示)
set ruler
" タブや改行を表示 (list:表示)
set list
" どの文字でタブや改行を表示するかを設定
set listchars=tab:>-,extends:<,trail:-,eol:$
" 全角スペース・行末のスペース・タブの可視化
if has("syntax")
    syntax on

   " PODバグ対策
    syn sync fromstart

    function! ActivateInvisibleIndicator()
        " 下の行の"　"は全角スペース
        syntax match InvisibleJISX0208Space "　" display containedin=ALL
        highlight InvisibleJISX0208Space term=underline ctermbg=Blue guibg=darkgray gui=underline
        "syntax match InvisibleTrailedSpace "[ \t]\+$" display containedin=ALL
        "highlight InvisibleTrailedSpace term=underline ctermbg=Red guibg=NONE gui=undercurl guisp=darkorange
        "syntax match InvisibleTab "\t" display containedin=ALL
        "highlight InvisibleTab term=underline ctermbg=white gui=undercurl guisp=darkslategray
    endf
    augroup invisible
        autocmd! invisible
        autocmd BufNew,BufRead * call ActivateInvisibleIndicator()
    augroup END
endif
" 長い行を折り返して表示 (nowrap:折り返さない)
set wrap
" 常にステータス行を表示 (詳細は:he laststatus)
set laststatus=2
" コマンドラインの高さ (Windows用gvim使用時はgvimrcを編集すること)
set cmdheight=2
" コマンドをステータス行に表示
set showcmd
" タイトルを表示
set title
" 画面を黒地に白にする (次行の先頭の " を削除すれば有効になる)
"colorscheme evening " (Windows用gvim使用時はgvimrcを編集すること)

"---------------------------------------------------------------------------
" ファイル操作に関する設定:
"
" バックアップファイルを作成しない (次行の先頭の " を削除すれば有効になる)
set nobackup
" テンポラリファイルを作成しない
set noswapfile




"---------------------------------------------------------------------------
" ファイル名に大文字小文字の区別がないシステム用の設定:
"   (例: DOS/Windows/MacOS)
"
if filereadable($VIM . '/vimrc') && filereadable($VIM . '/ViMrC')
  " tagsファイルの重複防止
  set tags=./tags,tags
endif

"---------------------------------------------------------------------------
" コンソールでのカラー表示のための設定(暫定的にUNIX専用)
if has('unix') && !has('gui_running') && !has('gui_macvim')
  let uname = system('uname')
  if uname =~? "linux"
    set term=builtin_linux
  elseif uname =~? "freebsd"
    set term=builtin_cons25
  elseif uname =~? "Darwin"
    set term=beos-ansi
  else
    set term=builtin_xterm
  endif
  unlet uname
endif

"---------------------------------------------------------------------------
" コンソール版で環境変数$DISPLAYが設定されていると起動が遅くなる件へ対応
if !has('gui_running') && has('xterm_clipboard')
  set clipboard=exclude:cons\\\|linux\\\|cygwin\\\|rxvt\\\|screen
endif

"---------------------------------------------------------------------------
" プラットホーム依存の特別な設定

" WinではPATHに$VIMが含まれていないときにexeを見つけ出せないので修正
if has('win32') && $PATH !~? '\(^\|;\)' . escape($VIM, '\\') . '\(;\|$\)'
  let $PATH = $VIM . ';' . $PATH
endif

if has('mac')
  " Macではデフォルトの'iskeyword'がcp932に対応しきれていないので修正
  set iskeyword=@,48-57,_,128-167,224-235
endif

" MacVim-KaoriYa固有の設定
"
if has('mac') && has('kaoriya')
  let $PATH = simplify($VIM . '/../../MacOS') . ':' . $PATH
  set migemodict=$VIMRUNTIME/dict/migemo-dict
  set migemo
endif

"---------------------------------------------------------------------------
" KaoriYaでバンドルしているプラグインのための設定

" autofmt: 日本語文章のフォーマット(折り返し)プラグイン.
set formatexpr=autofmt#japanese#formatexpr()

" vimdoc-ja: 日本語ヘルプを無効化する.
if has('win32') && kaoriya#switch#enabled('disable-vimdoc-ja')
  let &rtp = join(filter(split(&rtp, ','), 'v:val !~ "vimdoc-ja"'), ',')
endif

" Copyright (C) 2011 KaoriYa/MURAOKA Taro

"---------------------------------------------------------------------------
" ここから独自設定

"---------------------------------------------------------------------------
" PATHの追加
let $FTPLUGIN = $VIMRUNTIME . '\after\ftplugin'

"---------------------------------------------------------------------------
" プラグイン

" vim-pathogenの読み込み
"call pathogen#runtime_append_all_bundles()
" ヘルプコマンド
"call pathogen#helptags()

" NeoBundleの読み込み/設定
set nocompatible
filetype plugin indent off

if has('mac')
  echo 'has mac'
  let g:vimproc_dll_path = $VIMRUNTIME . '/autoload/vimproc_mac.so'
  echo g:vimproc_dll_path
elseif has('win32')
  let g:vimproc_dll_path = $VIMRUNTIME . '/bundle/vimproc/autoload/vimproc_win32.dll'
elseif has('win64')
  let g:vimproc_dll_path = $VIMRUNTIME . '/bundle/vimproc/autoload/vimproc_win64.dll'
endif

if has('vim_starting')
  set runtimepath+=$VIMRUNTIME/bundle/neobundle.vim/
endif
call neobundle#rc(expand('$VIMRUNTIME/bundle/'))

" originalrepos on github
NeoBundle 'Shougo/neobundle.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neocomplcache'
NeoBundle 'Shougo/vimproc'
NeoBundle 'Shougo/vimshell'
NeoBundle 'Shougo/neosnippet'
NeoBundle 'teramako/jscomplete-vim'
NeoBundle 'mattn/zencoding-vim'
NeoBundle 'git-mirror/vim-l9'
NeoBundle 'vim-scripts/FuzzyFinder'
NeoBundle 'vim-scripts/surround.vim'
NeoBundle 'taichouchou2/alpaca_powertabline'
NeoBundle 'Lokaltog/powerline', { 'rtp' : 'powerline/bindings/vim'}
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'ujihisa/vimshell-ssh'

NeoBundle 'digitaltoad/vim-jade'

filetype plugin indent on     " required!
syntax on

"---------------------------------------------------------------------------
" キーマッピング
nnoremap ZZ <Nop>

nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k
nnoremap <C-Up> 5k
nnoremap <C-Down> 5j

inoremap <C-z> <Esc>

"noremap <S-Up> v<Up>
"noremap <S-Down> v<Down>
"noremap <S-Left> v<Left>
"noremap <S-Right> v<Right>

"vnoremap <S-Up> <Up>
"vnoremap <S-Down> <Down>
"vnoremap <Up> v<Up>
"vnoremap <Down> v<Down>
"vnoremap <S-Left> <Left>
"vnoremap <S-Right> <Right>
"vnoremap <Left> v<Left>
"vnoremap <Right> v<Right>

"nnoremap <tab> f=2l
"nnoremap <s-tab> 2F=2l

" Save the current buffer and execute the Tortoise SVN interface's diff program
"noremap <silent> <leader>cc :w<CR>:execute "C:\Progra~1\TortoiseSVN\bin\TortoiseProc.exe /command:commit  /path:"%" /notempfile /closeonend:1"<CR>
"noremap <silent> <leader>cl :w<CR>:execute "C:\Progra~1\TortoiseSVN\bin\TortoiseProc.exe /command:log  /path:"%" /notempfile /closeonend:1"<CR>

" open new tab
nnoremap <c-n> :<c-u>tabnew<cr>

" change buffer
nnoremap gb :<C-u>bn<CR>
nnoremap gB :<C-u>bp<CR>
nnoremap cb :<C-u>bd<CR>

"Fuf setting
nnoremap <silent> <space>fb :FufBuffer!<CR>
nnoremap <silent> <space>ff :FufFile! <C-r>=expand('%:~:.')[:-1-len(expand('%:~:.:t'))]<CR><CR>
nnoremap <silent> <space>fd :FufDir! <C-r>=expand('%:p:~')[:-1-len(expand('%:p:~:t'))]<CR><CR>
nnoremap <silent> <space>fm :FufMruFile<CR>
nnoremap <silent> <Space>fc :FufRenewCache<CR>
autocmd FileType fuf nmap <C-c> <ESC>
let g:fuf_patternSeparator = ' '
let g:fuf_modesDisable = ['mrucmd']
let g:fuf_mrufile_exclude = '\v\.DS_Store|\.git|\.swp|\.svn'
let g:fuf_mrufile_maxItem = 100
let g:fuf_enumeratingLimit = 20
let g:fuf_file_exclude = '\v\.DS_Store|\.git|\.swp|\.svn'

" zencoding setting 
let g:user_zen_expandabbr_key = '<C-d>'
let g:user_zen_settings = {
\  'html' : {
\    'snippets' : {
\     'img:sp' : "<img src=\"[%url img=\"#SPACE#\"%]\" alt=\"\" width=\"1\" height=\"|\" style=\"border:none;\" />",
\    },
\  },
\}

" ---------------------------------------------------------------------------
"neocomまとめてコメントアウト
" neocomplcache setting 

"" Disable AutoComplPop.
"let g:acp_enableAtStartup = 0
"
"" enable neocomplcache
"let g:neocomplcache_enable_at_startup = 1
"
"" Set minimum syntax keyword length.
"let g:neocomplcache_min_syntax_length = 3
""let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'
"
"" Plugin key-mappings.
""imap <C-k>     <Plug>(neocomplcache_snippets_expand)
""smap <C-k>     <Plug>(neocomplcache_snippets_expand)
"inoremap <expr><C-g>     neocomplcache#undo_completion()
"inoremap <expr><C-l>     neocomplcache#complete_common_string()
"
"" SuperTab like snippets behavior.
"imap <expr><TAB> neocomplcache#sources#snippets_complete#expandable() ? "\<Plug>(neocomplcache_snippets_expand)" : pumvisible() ? "\<C-n>" : "\<TAB>"
"smap <expr><TAB> neocomplcache#sources#snippets_complete#expandable() ? "\<Plug>(neocomplcache_snippets_expand)" : pumvisible() ? "\<C-n>" : "\<TAB>"
"
"" Recommended key-mappings.
"" <CR>: close popup and save indent.
"inoremap <expr><CR>  neocomplcache#close_popup() . "\<CR>"
"" <TAB>: completion.
""inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
"
"" <C-h>, <BS>: close popup and delete backword char.
"inoremap <expr><C-h> neocomplcache#smart_close_popup()."\<C-h>"
"inoremap <expr><BS> neocomplcache#smart_close_popup()."\<C-h>"
"inoremap <expr><C-y>  neocomplcache#close_popup()
"inoremap <expr><C-e>  neocomplcache#cancel_popup()
"
"" For cursor moving in insert mode(Not recommended)
"inoremap <expr><Left>  neocomplcache#close_popup() . "\<Left>"
"inoremap <expr><Right> neocomplcache#close_popup() . "\<Right>"
"inoremap <expr><Up>    neocomplcache#close_popup() . "\<Up>"
"inoremap <expr><Down>  neocomplcache#close_popup() . "\<Down>"
"
"" AutoComplPop like behavior.
"let g:neocomplcace_enable_auto_select = 1
"
"" Shell like behavior(not recommended).
""set completeopt+=longest
""let g:neocomplcache_enable_auto_select = 1
""let g:neocomplcache_disable_auto_complete = 1
""inoremap <expr><TAB>  pumvisible() ? "\<Down>" : "\<C-x>\<C-u>"
""inoremap <expr><CR>  neocomplcache#smart_close_popup() . "\<CR>"
"
"" Enable omni completion.
"autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
"autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
"autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
"autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
"autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
"
"" Enable heavy omni completion.
"if !exists('g:neocomplcache_omni_patterns')
"  let g:neocomplcache_omni_patterns = {}
"endif
""let g:neocomplcache_omni_patterns.ruby = '[^. *\t]\.\h\w*\|\h\w*::'
""autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
""let g:neocomplcache_omni_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
""let g:neocomplcache_omni_patterns.c = '\%(\.\|->\)\h\w*'
""let g:neocomplcache_omni_patterns.cpp = '\h\w*\%(\.\|->\)\h\w*\|\h\w*::'
""
"neocomまとめてコメントアウト

" Enable jscomplete-vim
autocmd FileType javascript setlocal omnifunc=jscomplete#CompleteJS
let g:jscomplete_use = ['dom']

" For snippet_complete marker.
if has('conceal')
  set conceallevel=2 concealcursor=i
endif


" ---------------------------------------------------------------------------
" 編集関連

"クリップボードをOSと連携
if has('win32')
  set clipboard=unnamed
else
  set clipboard=unnamed,autoselect
endif
"カーソルを行頭、行末で止まらないようにする
set whichwrap=b,s,h,l,<,>,[,]

"---------------------------------------------------------------------------
" UI関連
"入力モード時、ステータスラインのカラーを変更
augroup InsertHook
autocmd!
autocmd InsertEnter * highlight StatusLine guifg=#ccdc90 guibg=#2E4340
autocmd InsertLeave * highlight StatusLine guifg=#2E4340 guibg=#ccdc90
augroup END

" powerlineの設定
"set guifont=Inconsolata_for_Powerline:h11:cANSI
set guifont=Ricty-Regular:h11:cDEFAULT
let g:Powerline_symbols='fancy'
"call Pl#Hi#Allocate({
"  \ 'black'          : 16,
"  \ 'white'          : 231,
"  \
"  \ 'darkestgreen'   : 22,
"  \ 'darkgreen'      : 28,
"  \
"  \ 'darkestcyan'    : 23,
"  \ 'mediumcyan'     : 117,
"  \
"  \ 'darkestblue'    : 24,
"  \ 'darkblue'       : 31,
"  \
"  \ 'darkestred'     : 52,
"  \ 'darkred'        : 88,
"  \ 'mediumred'      : 124,
"  \ 'brightred'      : 160,
"  \ 'brightestred'   : 196,
"  \
"  \
"  \ 'darkestyellow'  : 59,
"  \ 'darkyellow'     : 100,
"  \ 'darkestpurple'  : 55,
"  \ 'mediumpurple'   : 98,
"  \ 'brightpurple'   : 189,
"  \
"  \ 'brightorange'   : 208,
"  \ 'brightestorange': 214,
"  \
"  \ 'gray0'          : 233,
"  \ 'gray1'          : 235,
"  \ 'gray2'          : 236,
"  \ 'gray3'          : 239,
"  \ 'gray4'          : 240,
"  \ 'gray5'          : 241,
"  \ 'gray6'          : 244,
"  \ 'gray7'          : 245,
"  \ 'gray8'          : 247,
"  \ 'gray9'          : 250,
"  \ 'gray10'         : 252,
"  \ })
"
" 'n': normal mode
" 'i': insert mode
" 'v': visual mode
" 'r': replace mode
" 'N': not active
"let g:Powerline#Colorschemes#my#colorscheme = Pl#Colorscheme#Init([
"  \ Pl#Hi#Segments(['SPLIT'], {
"    \ 'n': ['white', 'gray2'],
"    \ 'N': ['gray0', 'gray0'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['mode_indicator'], {
"    \ 'i': ['darkestgreen', 'white', ['bold']],
"    \ 'n': ['darkestcyan', 'white', ['bold']],
"    \ 'v': ['darkestpurple', 'white', ['bold']],
"    \ 'r': ['mediumred', 'white', ['bold']],
"    \ 's': ['white', 'gray5', ['bold']],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['fileinfo', 'filename'], {
"    \ 'i': ['white', 'darkgreen', ['bold']],
"    \ 'n': ['white', 'darkblue', ['bold']],
"    \ 'v': ['white', 'mediumpurple', ['bold']],
"    \ 'r': ['white', 'brightred', ['bold']],
"    \ 'N': ['gray0', 'gray2', ['bold']],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['branch', 'scrollpercent', 'raw', 'filesize'], {
"    \ 'n': ['gray2', 'gray7'],
"    \ 'N': ['gray0', 'gray2'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['fileinfo.filepath', 'status'], {
"    \ 'n': ['gray10'],
"    \ 'N': ['gray5'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['static_str'], {
"    \ 'n': ['white', 'gray4'],
"    \ 'N': ['gray1', 'gray1'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['fileinfo.flags'], {
"    \ 'n': ['white'],
"    \ 'N': ['gray4'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['currenttag', 'fileformat', 'fileencoding', 'pwd', 'filetype', 'rvm:string', 'rvm:statusline', 'virtualenv:statusline', 'charcode', 'currhigroup'], {
"    \ 'n': ['gray9', 'gray4'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['lineinfo'], {
"    \ 'n': ['gray2', 'gray10'],
"    \ 'N': ['gray2', 'gray4'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['errors'], {
"    \ 'n': ['brightestorange', 'gray2', ['bold']],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['lineinfo.line.tot'], {
"    \ 'n': ['gray2'],
"    \ 'N': ['gray2'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['paste_indicator', 'ws_marker'], {
"    \ 'n': ['white', 'brightred', ['bold']],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['gundo:static_str.name', 'command_t:static_str.name'], {
"    \ 'n': ['white', 'mediumred', ['bold']],
"    \ 'N': ['brightred', 'darkestred', ['bold']],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['gundo:static_str.buffer', 'command_t:raw.line'], {
"    \ 'n': ['white', 'darkred'],
"    \ 'N': ['brightred', 'darkestred'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['gundo:SPLIT', 'command_t:SPLIT'], {
"    \ 'n': ['white', 'darkred'],
"    \ 'N': ['white', 'darkestred'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['ctrlp:focus', 'ctrlp:byfname'], {
"    \ 'n': ['brightpurple', 'darkestpurple'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['ctrlp:prev', 'ctrlp:next', 'ctrlp:pwd'], {
"    \ 'n': ['white', 'mediumpurple'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['ctrlp:item'], {
"    \ 'n': ['darkestpurple', 'white', ['bold']],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['ctrlp:marked'], {
"    \ 'n': ['brightestred', 'darkestpurple', ['bold']],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['ctrlp:count'], {
"    \ 'n': ['darkestpurple', 'white'],
"    \ }),
"  \
"  \ Pl#Hi#Segments(['ctrlp:SPLIT'], {
"    \ 'n': ['white', 'darkestpurple'],
"    \ }),
"  \ ])
let g:Powerline_colorscheme='skwp'
" ステータスラインに文字コードと改行文字を表示する
" set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P
"set statusline=%{expand('%:p:t')}\ %<\(%{SnipMid(expand('%:p:h'),80-len(expand('%:p:t')),'...')}\)%=\ %m%r%y%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}[%3l,%3c]%8P

" FuzzyFinderから長いパスの中間を省略する関数をパクって最適化する
" http://hail2u.net/blog/software/optimize-vim-statusline.html
function! SnipMid(str, len, mask)
  if a:len >= len(a:str)
    return a:str
  elseif a:len <= len(a:mask)
    return a:mask
  endif

  let len_head = (a:len - len(a:mask)) / 2
  let len_tail = a:len - len(a:mask) - len_head

  return (len_head > 0 ? a:str[: len_head - 1] : '') . a:mask . (len_tail > 0 ? a:str[-len_tail :] : '')
endfunction

"---------------------------------------------------------------------------
" ファイル設定関連

" filetype を検出
filetype on

" fileencode を設定
set fileencodings=utf-8,euc-jp,sjis,cp932

" Smartyのsyntax-highlightを有効にする(したい)
"augroup filetypedetect
"    autocmd! BufNewFile,BufRead *.html setfiletype html
"    autocmd! BufNewFile,BufRead *.html setfiletype smarty
"augroup END

" Smarty.vim delimiter setting
"syn region smartyZone matchgroup=Delimiter start="\[%" end="%\]" contains=smartyProperty, smartyString, smartyBlock, smartyTagName, smartyConstant, smartyInFunc, smartyModifier

au BufNewFile,BufRead *.md setfiletype markdown
au BufNewFile,BufRead *.jade setfiletype jade
" vimにcoffeeファイルタイプを認識させる
au BufRead,BufNewFile,BufReadPre *.coffee   set filetype=coffee
" インデントを設定
autocmd FileType coffee     setlocal sw=2 sts=2 ts=2
"augroup filetypedetect
"    autocmd! BufNewFile,BufRead *.md setfiletype markdown
"augroup END

"---------------------------------------------------------------------------
" vimrcを良い感じに開く
let s:vimrcbody = '$VIM/vimrc'
let s:gvimrcbody = '$VIM/gvimrc'
let $MYVIMRC = expand(s:vimrcbody)
let $MYGVIMRC = expand(s:gvimrcbody)

function! OpenFile(file)
  let empty_buffer = line('$') == 1 && strlen(getline('1')) == 0
  if empty_buffer && !&modified
    execute 'e ' . a:file
  else
    execute 'tabnew ' . a:file
  endif
endfunction
command! OpenMyVimrc call OpenFile(s:vimrcbody)
command! OpenMyGVimrc call OpenFile(s:gvimrcbody)
nnoremap ,, :<C-u>OpenMyVimrc<CR>
nnoremap ,<Tab> :<C-u>OpenMyGVimrc<CR>

" F5でリロード
function! SourceIfExists(file)
  if filereadable(expand(a:file))
    execute 'source ' . a:file
  endif
  echo 'Reloaded vimrc and gvimrc and ' . a:file . '.'
  FullScreen
endfunction
nnoremap <F5> <Esc>:<C-u>source $MYVIMRC<CR> :source $MYGVIMRC<CR> :call SourceIfExists($FTPLUGIN .'\'. &filetype . '.vim')<CR>

" Map double-tap Esc to clear search highlights
nnoremap <silent> <Esc><Esc> <Esc>:nohlsearch<CR><Esc>

" vimgrepで自動的にQuickFixを開く
au QuickFixCmdPost vimgrep cw

" Macっぽくペイン切り替え
nnoremap <silent> <M-D-Right> <Esc><C-w>l
nnoremap <silent> <M-D-Left> <Esc><C-w>h
nnoremap <silent> <M-D-Up> <Esc><C-w>k
nnoremap <silent> <M-D-Down> <Esc><C-w>j
"
"---------------------------------------------------------------------------
" VimShellを良い感じに開く
"
nnoremap <silent> ,vs :VimShell<CR>

"---------------------------------------------------------------------------
" スペースインデントに再設定
nnoremap <silent> ,si :set softtabstop=2 tabstop=2 shiftwidth=2 expandtab<CR>

"---------------------------------------------------------------------------
" for surround.vim
" [key map]
" 1 : <h1>|</h1>
" 2 : <h2>|</h2>
" 3 : <h3>|</h3>
" 4 : <h4>|</h4>
" 5 : <h5>|</h5>
" 6 : <h6>|</h6>
"
" p : <p>|</p>
" u : <ul>|</ul>
" o : <ol>|</ol>
" l : <li>|</li>
" a : <a href="">|</a>
" A : <a href="|"></a>
" i : <img src="|" alt="">
" I : <img src="" alt="|">
" d : <div>|</div>
" D : <div class="section">|</div>

autocmd FileType html let b:surround_49  = "<h1>\r</h1>"
autocmd FileType html let b:surround_50  = "<h2>\r</h2>"
autocmd FileType html let b:surround_51  = "<h3>\r</h3>"
autocmd FileType html let b:surround_52  = "<h4>\r</h4>"
autocmd FileType html let b:surround_53  = "<h5>\r</h5>"
autocmd FileType html let b:surround_54  = "<h6>\r</h6>"

autocmd FileType html let b:surround_112 = "<p>\r</p>"
autocmd FileType html let b:surround_117 = "<ul>\r</ul>"
autocmd FileType html let b:surround_111 = "<ol>\r</ol>"
autocmd FileType html let b:surround_108 = "<li>\r</li>"
autocmd FileType html let b:surround_97  = "<a href=\"\">\r</a>"
autocmd FileType html let b:surround_65  = "<a href=\"\r\"></a>"
autocmd FileType html let b:surround_105 = "<img src=\"\r\" alt=\"\">"
autocmd FileType html let b:surround_73  = "<img src=\"\" alt=\"\r\">"
autocmd FileType html let b:surround_100 = "<div>\r</div>"
autocmd FileType html let b:surround_68  = "<div class=\"section\">\r</div>"

"---------------------------------------------------------------------------
" quickhl 設定
"nmap <Space>m <Plug>(quickhl-toggle)
"xmap <Space>m <Plug>(quickhl-toggle)
"nmap <Space>M <Plug>(quickhl-reset)
"xmap <Space>M <Plug>(quickhl-reset)
"nmap <Space>j <Plug>(quickhl-match)
"
"let g:quickhl_keywords = [
"    \ "\[%(.*)%\]",
"    \ ]

"---------------------------------------------------------------------------
" indent_guides
" インデントの深さに色を付ける
let g:indent_guides_start_level=2
let g:indent_guides_auto_colors=0
let g:indent_guides_enable_on_vim_startup=0
let g:indent_guides_color_change_percent=20
let g:indent_guides_guide_size=1
let g:indent_guides_space_guides=1

hi IndentGuidesOdd  ctermbg=235
hi IndentGuidesEven ctermbg=237
au FileType coffee,ruby,javascript,python IndentGuidesEnable
nmap <silent><Leader>ig <Plug>IndentGuidesToggle

" 半透明(gvimrcでなぜかダメだった)
set transparency=20
nmap + :set transparency+=5<CR>
nmap _ :set transparency-=5<CR>
